CREATE SCHEMA IF NOT EXISTS gms;

CREATE EXTENSION IF NOT EXISTS timescaledb;

CREATE TABLE IF NOT EXISTS gms.telemetry_reading (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    greenhouse_id TEXT NOT NULL,
    zone_id TEXT NOT NULL,
    device_id TEXT NOT NULL,
    sensor_key TEXT NOT NULL,
    value DOUBLE PRECISION NOT NULL,
    unit TEXT NOT NULL,
    status TEXT NOT NULL,
    observed_at TIMESTAMPTZ NOT NULL,
    ingested_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

DO $$
BEGIN
    PERFORM create_hypertable('gms.telemetry_reading', 'observed_at', if_not_exists => TRUE);
EXCEPTION
    WHEN undefined_function THEN
        RAISE NOTICE 'TimescaleDB create_hypertable function is unavailable.';
END;
$$;

DO $$
BEGIN
    PERFORM add_retention_policy('gms.telemetry_reading', INTERVAL '90 days', if_not_exists => TRUE);
EXCEPTION
    WHEN undefined_function THEN
        RAISE NOTICE 'TimescaleDB add_retention_policy function is unavailable.';
END;
$$;

CREATE INDEX IF NOT EXISTS idx_telemetry_scope_ts
    ON gms.telemetry_reading (greenhouse_id, zone_id, observed_at DESC);

CREATE INDEX IF NOT EXISTS idx_telemetry_device_ts
    ON gms.telemetry_reading (greenhouse_id, device_id, observed_at DESC);

CREATE TABLE IF NOT EXISTS gms.latest_metric (
    greenhouse_id TEXT NOT NULL,
    zone_id TEXT NOT NULL,
    device_id TEXT NOT NULL,
    sensor_key TEXT NOT NULL,
    value DOUBLE PRECISION NOT NULL,
    unit TEXT NOT NULL,
    status TEXT NOT NULL,
    last_updated_at TIMESTAMPTZ NOT NULL,
    PRIMARY KEY (greenhouse_id, device_id, sensor_key)
);

CREATE INDEX IF NOT EXISTS idx_latest_metric_zone
    ON gms.latest_metric (greenhouse_id, zone_id, sensor_key);

CREATE TABLE IF NOT EXISTS gms.zone_device (
    tenant_id TEXT NOT NULL,
    greenhouse_id TEXT NOT NULL,
    device_id TEXT NOT NULL,
    zone_id TEXT,
    zone_name TEXT,
    firmware_version TEXT,
    status TEXT NOT NULL,
    last_seen_at TIMESTAMPTZ NOT NULL,
    updated_at TIMESTAMPTZ NOT NULL,
    metadata JSONB NOT NULL DEFAULT '{}'::jsonb,
    removed_at TIMESTAMPTZ,
    PRIMARY KEY (tenant_id, greenhouse_id, device_id)
);

CREATE INDEX IF NOT EXISTS idx_zone_device_greenhouse
    ON gms.zone_device (tenant_id, greenhouse_id, removed_at, status, zone_name, device_id);

CREATE TABLE IF NOT EXISTS gms.command_ack (
    command_id TEXT PRIMARY KEY,
    event_id TEXT,
    type TEXT,
    tenant_id TEXT,
    greenhouse_id TEXT,
    gateway_id TEXT,
    device_id TEXT,
    zone_id TEXT,
    status TEXT,
    reason TEXT,
    ack_timestamp TIMESTAMPTZ,
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_command_ack_scope
    ON gms.command_ack (tenant_id, greenhouse_id, device_id, updated_at DESC);

CREATE TABLE IF NOT EXISTS gms.alert_event (
    id TEXT PRIMARY KEY,
    severity TEXT NOT NULL,
    sensor_key TEXT,
    message TEXT NOT NULL,
    triggered_at TIMESTAMPTZ NOT NULL,
    acknowledged BOOLEAN NOT NULL DEFAULT FALSE,
    dismissed_at TIMESTAMPTZ
);

CREATE INDEX IF NOT EXISTS idx_alert_event_active
    ON gms.alert_event (dismissed_at, acknowledged, triggered_at DESC);
