CREATE TABLE IF NOT EXISTS gms.tenant (
    tenant_id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS gms.app_user (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username TEXT NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS gms.tenant_membership (
    user_id BIGINT NOT NULL,
    tenant_id TEXT NOT NULL,
    role TEXT NOT NULL DEFAULT 'ADMIN',
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (user_id, tenant_id),
    CONSTRAINT fk_membership_user FOREIGN KEY (user_id) REFERENCES gms.app_user(id) ON DELETE CASCADE,
    CONSTRAINT fk_membership_tenant FOREIGN KEY (tenant_id) REFERENCES gms.tenant(tenant_id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS gms.greenhouse (
    tenant_id TEXT NOT NULL,
    greenhouse_id TEXT NOT NULL,
    gateway_id TEXT NOT NULL,
    name TEXT NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    PRIMARY KEY (tenant_id, greenhouse_id),
    CONSTRAINT fk_greenhouse_tenant FOREIGN KEY (tenant_id) REFERENCES gms.tenant(tenant_id) ON DELETE CASCADE,
    CONSTRAINT uq_greenhouse_gateway UNIQUE (tenant_id, gateway_id)
);

INSERT INTO gms.tenant(tenant_id, name)
VALUES ('tenant-demo', 'Demo Tenant')
ON CONFLICT (tenant_id) DO NOTHING;

INSERT INTO gms.tenant(tenant_id, name)
SELECT DISTINCT tenant_id, tenant_id
FROM gms.zone_device
WHERE tenant_id IS NOT NULL
ON CONFLICT (tenant_id) DO NOTHING;

INSERT INTO gms.greenhouse(tenant_id, greenhouse_id, gateway_id, name)
VALUES ('tenant-demo', 'greenhouse-demo', 'greenhouse-demo', 'Demo Greenhouse')
ON CONFLICT (tenant_id, greenhouse_id) DO NOTHING;

INSERT INTO gms.greenhouse(tenant_id, greenhouse_id, gateway_id, name)
SELECT DISTINCT tenant_id, greenhouse_id, greenhouse_id, greenhouse_id
FROM gms.zone_device
WHERE tenant_id IS NOT NULL AND greenhouse_id IS NOT NULL
ON CONFLICT (tenant_id, greenhouse_id) DO NOTHING;

ALTER TABLE gms.telemetry_reading
    ADD COLUMN IF NOT EXISTS tenant_id TEXT;

UPDATE gms.telemetry_reading
SET tenant_id = 'tenant-demo'
WHERE tenant_id IS NULL;

ALTER TABLE gms.telemetry_reading
    ALTER COLUMN tenant_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_telemetry_tenant_scope_ts
    ON gms.telemetry_reading (tenant_id, greenhouse_id, zone_id, observed_at DESC);

CREATE INDEX IF NOT EXISTS idx_telemetry_tenant_device_ts
    ON gms.telemetry_reading (tenant_id, greenhouse_id, device_id, observed_at DESC);

ALTER TABLE gms.latest_metric
    ADD COLUMN IF NOT EXISTS tenant_id TEXT;

UPDATE gms.latest_metric
SET tenant_id = 'tenant-demo'
WHERE tenant_id IS NULL;

ALTER TABLE gms.latest_metric
    ALTER COLUMN tenant_id SET NOT NULL;

ALTER TABLE gms.latest_metric
    DROP CONSTRAINT IF EXISTS latest_metric_pkey;

ALTER TABLE gms.latest_metric
    ADD CONSTRAINT latest_metric_pkey
    PRIMARY KEY (tenant_id, greenhouse_id, device_id, sensor_key);

CREATE INDEX IF NOT EXISTS idx_latest_metric_tenant_zone
    ON gms.latest_metric (tenant_id, greenhouse_id, zone_id, sensor_key);

ALTER TABLE gms.alert_event
    ADD COLUMN IF NOT EXISTS tenant_id TEXT,
    ADD COLUMN IF NOT EXISTS greenhouse_id TEXT;

UPDATE gms.alert_event
SET tenant_id = COALESCE(tenant_id, 'tenant-demo'),
    greenhouse_id = COALESCE(greenhouse_id, 'greenhouse-demo')
WHERE tenant_id IS NULL OR greenhouse_id IS NULL;

ALTER TABLE gms.alert_event
    ALTER COLUMN tenant_id SET NOT NULL,
    ALTER COLUMN greenhouse_id SET NOT NULL;

CREATE INDEX IF NOT EXISTS idx_alert_event_tenant_active
    ON gms.alert_event (tenant_id, greenhouse_id, dismissed_at, acknowledged, triggered_at DESC);
